language: java
dist: precise
jdk:
  - oraclejdk8
services:
   - redis-server
before_script:
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update
- sudo apt-get install google-chrome-stable
script: 
   - ./gradlew build
#   - ./gradlew gateleen-test:startServer  (also waits for it to come up)
#   - ./gradlew gateleen-playground:uploapStaticFiles
#   - ./gradlew gateleen-test:stopServer
   - ./gradlew :gateleen-test:test -PintegrationTests
   - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)