language: java
dist: precise
sudo: false
jdk:
  - oraclejdk8
services:
   - redis-server
addons:
  apt:
    packages:
         - google-chrome-stable
before_script:
     - export DISPLAY=:99.0
     - sh -e /etc/init.d/xvfb start &
     - sleep 3
script: 
   - ./gradlew build
#   - ./gradlew gateleen-test:startServer  (also waits for it to come up)
#   - ./gradlew gateleen-playground:uploapStaticFiles
#   - ./gradlew gateleen-test:stopServer
   - ./gradlew :gateleen-test:test -PintegrationTests
   - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
